CREATE TABLE [History]
(
[Id] INT IDENTITY PRIMARY KEY,
[Logger_Password] NVARCHAR(255) NOT NULL,
);

CREATE TABLE [Password]
(
[Id] INT IDENTITY PRIMARY KEY,
[Id_Logger] INT UNIQUE FOREIGN KEY REFERENCES [History](Id) NULL,
[Password_Hash] NVARCHAR(255) NOT NULL,
[Set_Date] DATE DEFAULT GETDATE(),
);

CREATE TABLE [Account]
(
[Id] INT IDENTITY PRIMARY KEY,
[Login] NVARCHAR(26) UNIQUE NOT NULL,
[Id_Password] INT UNIQUE FOREIGN KEY REFERENCES [Password](Id),
);

CREATE TABLE [User]
(
[Id] INT IDENTITY PRIMARY KEY,
[Id_Account] INT UNIQUE FOREIGN KEY REFERENCES [Account](Id),
);
